{% set version = "0.5" %}

package:
    name: dxfile
    version: {{ version }}

source:
    url: https://github.com/data-exchange/dxfile/archive/v{{ version }}.tar.gz
    fn: dxfile-{{ version }}.tar.gz
    sha256: 6317fa9f1b4f12039ca68eab2d9c96d95930499d084f5802a02bb49c5fb1c88d

build:
    noarch: python
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
    host:
        - pip
        - python
        - setuptools
    run:
        - python
        - h5py

test:
    imports:
        - dxfile
        - dxfile.dxtomo

about:
    home: http://dxfile.readthedocs.org
    license: BSD 3-Clause
    summary: 'Reader/Writer for Data Exchange files.'

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - ericdill
        - licode
        - ravescovi
        - tacaswell
