{% set version = "0.4" %}

package:
    name: dxfile
    version: {{ version }}

source:
    url: https://github.com/data-exchange/dxfile/archive/v{{ version }}.tar.gz
    fn: dxfile-{{ version }}.tar.gz
    sha256: b7729eebdc7c99a66a8b339fc10019aa8565e02bd12708540fb3f47935f004c7

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - h5py

test:
    imports:
        - dxfile
        - dxfile.dxtomo

about:
    home: http://dxfile.readthedocs.org
    license: BSD 3-Clause
    summary: 'Reader/Writer for Data Exchange files.'

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - ericdill
        - licode
        - ravescovi
        - tacaswell
