travis:
  secure:
    BINSTAR_TOKEN: HJhLqvRNflj1d16yFbN/op+gIrIKddInZMrc4ufDvM2KldVdGfpO3efocrnzToO22zZQIDbKvkSze9YFycSx7QMZ6cjuETF/Dl9by1g3QddObhIJN0UTMBOOVFSyDQ52IYZvHeHmo49w7bgiD34bGUnkjB+1as7HkylNeutYeZR63TzrgPiisZJEb0uaVaZzKVcK8Ojrvfe4mCDg9yinAg64UsPKk8DMnjgMhcmQox6marX+Bw9iWB9zCSF4E+PmHBlrElV5MxTgsDdmggS0J3qJyl0+h24jopG2FTSWQseKBS5DBNK4uq/GaB5tim3daUuxK6flYQrtW3bIOy5JX/aB7SgWRHCz0JGOgBkHPSEVJvkK9Xw+NV0lIPPZxc8+Yk5L7ROfzCwPmcpTFHEHL0ZwhGQnxNpdAns/NIWcCUz0/lwh6Qzl9AdDH5AdfSEjuMP5QEkKPhbXjX+0H/YPSBM0LBmUEbM1KqwR1I8XOUDydgtIpYVX3AhYfKgW+Uu1bIK6+YZLdC/4xguRMZJ7BnzUIZnvOFTWXvf6jBF8Q0JZNDBt9VWb9rFWxbV3gu8ALKsevsFN54ukludrWOWDnHePGY27CCwTa/3Gfq8wOCJcVqBl2AkJJUcnXEllGjHfEaTvPqHoVjKwCnXo6Wo99ns253yJMOnByAMsY+o2LyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
